#
# Autogenerated by Thrift Compiler (0.7.0)
#
# DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
#

from thrift.Thrift import *
from ttypes import *

VERSION = "1.1.0"
GabrielEventParams = {
    0 : "string",
    1 : "from",
    2 : "to",
    3 : "app",
    4 : "sid",
    5 : "action",
    6 : "devicename",
    7 : "devicemac",
    8 : "username",
    9 : "password",
    10 : "localip",
    11 : "version",
    12 : "action_result",
    13 : "url",
    14 : "ip",
    15 : "port",
    16 : "id8",
    17 : "ip_stunt1",
    18 : "ip_stunt2",
    19 : "ip_relay",
    20 : "port_http",
    21 : "port_https",
    22 : "capability",
    23 : "accesskey",
    24 : "port_liveview",
    25 : "port_playback",
    26 : "proxy",
    27 : "register_status",
    28 : "peer_id8",
    29 : "system_version",
    30 : "relay_ctrl_port",
    31 : "relay_data_port",
    32 : "device_ext_ip",
    38 : "event_src_ip",
    39 : "event_dst_ip",
    40 : "chunk_type",
    4096 : "integer",
    4097 : "tid",
    4098 : "status",
    4099 : "err",
    4100 : "event_id",
    4101 : "chunk_number",
    4352 : "event_time",
    8192 : "binary",
    8193 : "payload",
    8194 : "encrypt_b64",
    8195 : "tunnel_key",
    8196 : "chunk_data",
}
EVT_UNREAD_COUNTER = "unread"
EVT_ACKALL_MARKER = "ack_all_marker"
EVT_CLN_MARKER = "clean_marker"
EVT_SEVERITY = "severity"
EVT_PRI = "pri"
EVT_ACKED = "acked"
EVT_ACKED_TRUE = "true"
EVT_CREATE_TIME = "create_time"
